### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by lebron-2016** [liaopan-lp/MO-YOLO#1]
Dear author, 

I recently read your paper and would like to ask when will you make the code public? 

Hope to learn further from your work.

Thanks!

**Comment by lebron-2016** [comment]
> Yes, this work will be open source in the future, but it may be in April next year (after all, the deadline for ECCV will be in March next year). If you are in a hurry, send me an email by the end of February next year, and I can give you an unorganized version. 这个东西我现在还没有搞完（师兄要毕业，一堆人跟我抢显卡），arxiv上那个就是占位置的，大体结构是那样的。最近再试各种trick提点，这玩意训练速度确实快。推理速度的话，目前优化有点问题，2080ti和4090推理是一个速度，都是72ms左右。 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liaopan-lp/MO-YOLO" ***@***.***&gt;; 发送时间:&nbsp;2023年12月4日(星期一) 晚上9:49 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[liaopan-lp/MO-YOLO] Code (Issue #1) Dear author, I recently read your paper and would like to ask when will you make the code public? Hope to learn further from your work. Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的好的，感谢！

**Comment by lebron-2016** [comment]
您好，请问您有试过训练MOTR模型的BDD100K分支吗？cuda、torch和torchvision的版本分别使用多少呢？

**Comment by liaopan-lp** [comment]
没有，BDD100k太大了，没试过。我自己论文之后打算用KITTI




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月17日(星期天) 晚上7:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [liaopan-lp/MO-YOLO] Code (Issue #1)





 
您好，请问您有试过训练MOTR模型的BDD100K分支吗？cuda、torch和torchvision的版本分别使用多少呢？

**Comment by lebron-2016** [comment]
您好，还想请教一下，您的encoder是如何利用yolov8和RT-DETR的？有使用到Deformable Detr的encoder吗？对下面这句话不是很理解，希望能得到您的解答！感谢！！
![image](https://github.com/liaopan-lp/MO-YOLO/assets/80045218/13db2e14-e736-44de-a760-51d5c4d21fd0)

**Comment by liaopan-lp** [comment]
Our model does not use an encoder, it is a decoder only model like GPT. Thanks to its faster convergence and running speed compared to MOTR. Our latest version of the paper will be released soon. 

There are currently two ways to initialize weights: one is random initialization, and the other is to read the pre-trained weights of YOLOv8 and RT-DETR on coco (in fact, it is more reasonable to refine the model as a detection model on Coco).


应该就明后天了，最晚31号，要准备回家过年了，初稿要赶紧写完。

> 您好，还想请教一下，您的encoder是如何利用yolov8和RT-DETR的？有使用到Deformable Detr的encoder吗？对下面这句话不是很理解。
> 
> ![image](https://private-user-images.githubusercontent.com/80045218/299271530-13db2e14-e736-44de-a760-51d5c4d21fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTE3NDgsIm5iZiI6MTcwNjA5MTQ0OCwicGF0aCI6Ii84MDA0NTIxOC8yOTkyNzE1MzAtMTNkYjJlMTQtZTczNi00NGRlLWE3NjAtNTFkNWM0ZDIxZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOGQ4NWEzY2VjZTllOTQ0ODcyYjQ4ZGJhYTI0NGY5MjRkZGM4M2FkYTIwY2M3MWUxOGE0YjY4ODNhMjZlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.62EpdfKner_gwjVkP1dyaN9brJtgMP3clr38p2qbfYE)
> 
> 以及，实验时模型的初始化权重是怎样的？
> 
> ![image](https://private-user-images.githubusercontent.com/80045218/299273823-92695927-e545-4fed-aacb-2b142bf38681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTE3NDgsIm5iZiI6MTcwNjA5MTQ0OCwicGF0aCI6Ii84MDA0NTIxOC8yOTkyNzM4MjMtOTI2OTU5MjctZTU0NS00ZmVkLWFhY2ItMmIxNDJiZjM4NjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNDE2OGI1MGRmOGE4M2JjMTgwMzg3NDBiZWRkZjY1OWQyZjhiMWE3MGIzYmY1ZmNhOWM1YmM3OGEwNzI1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uP71-AU72DnndwBsZBHQ2bRxOXbOKK04wJTcrx92FCM)
> 
> 希望能得到您的解答！感谢！！

**Comment by lebron-2016** [comment]
> Our model does not use an encoder, it is a decoder only model like GPT. Thanks to its faster convergence and running speed compared to MOTR. Our latest version of the paper will be released soon.
> 
> There are currently two ways to initialize weights: one is random initialization, and the other is to read the pre-trained weights of YOLOv8 and RT-DETR on coco (in fact, it is more reasonable to refine the model as a detection model on Coco).
> 
> 应该就明后天了，最晚31号，要准备回家过年了，初稿要赶紧写完。
> 
> > 您好，还想请教一下，您的encoder是如何利用yolov8和RT-DETR的？有使用到Deformable Detr的encoder吗？对下面这句话不是很理解。
> > ![image](https://private-user-images.githubusercontent.com/80045218/299271530-13db2e14-e736-44de-a760-51d5c4d21fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTE3NDgsIm5iZiI6MTcwNjA5MTQ0OCwicGF0aCI6Ii84MDA0NTIxOC8yOTkyNzE1MzAtMTNkYjJlMTQtZTczNi00NGRlLWE3NjAtNTFkNWM0ZDIxZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOGQ4NWEzY2VjZTllOTQ0ODcyYjQ4ZGJhYTI0NGY5MjRkZGM4M2FkYTIwY2M3MWUxOGE0YjY4ODNhMjZlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.62EpdfKner_gwjVkP1dyaN9brJtgMP3clr38p2qbfYE)
> > 以及，实验时模型的初始化权重是怎样的？
> > ![image](https://private-user-images.githubusercontent.com/80045218/299273823-92695927-e545-4fed-aacb-2b142bf38681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTE3NDgsIm5iZiI6MTcwNjA5MTQ0OCwicGF0aCI6Ii84MDA0NTIxOC8yOTkyNzM4MjMtOTI2OTU5MjctZTU0NS00ZmVkLWFhY2ItMmIxNDJiZjM4NjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNDE2OGI1MGRmOGE4M2JjMTgwMzg3NDBiZWRkZjY1OWQyZjhiMWE3MGIzYmY1ZmNhOWM1YmM3OGEwNzI1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uP71-AU72DnndwBsZBHQ2bRxOXbOKK04wJTcrx92FCM)
> > 希望能得到您的解答！感谢！！

感谢您的解答！！

所以您大概是利用RT-DETR产生的token送入decoder做跟踪吗？

期待您的工作！！

**Comment by liaopan-lp** [comment]
Not quite accurate, you can take a look at the MOTR paper. The process I have here is consistent with it.
不太准确，这里您可以去看一下MOTR的论文，我这里的过程和原理它是一致的。这个过程MOTR的那几个改进版（除了MOTRv2外）应该都是差不多的。

> 所以您大概是利用RT-DETR产生的query送入decoder做跟踪吗？
> 
> 期待您的工作！！

**Comment by lebron-2016** [comment]
> Not quite accurate, you can take a look at the MOTR paper. The process I have here is consistent with it. 不太准确，这里您可以去看一下MOTR的论文，我这里的过程和原理它是一致的。这个过程MOTR的那几个改进版（除了MOTRv2外）应该都是差不多的。
> 
> > 所以您大概是利用RT-DETR产生的query送入decoder做跟踪吗？
> > 期待您的工作！！

嗯嗯好的，谢谢您！！

请问方便加下微信吗？weixin：Clevelandss
